---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 100
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      ignore_warnings: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - ToDo
      - Todo
      - TO-DO
      - To-Do
      - HACK
      - Hack
      - HERE BE DRAGONS
      - Here Be Dragons
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- ".*"
- node_modules/
- "**/reports/**/*"
- "**/test/**/*"
